function wikipedia(page) {
    return { type: 'wikipedia', page };
}

function url(urlValue, title) {
    return { type: 'url', url: urlValue, title };
}

function repo(repoName) {
    return { type: 'githubRepo', repo: repoName };
}

function entry(term, title, category, sources, options = {}) {
    return {
        term,
        title,
        category,
        sources,
        aliases: options.aliases || [],
        tags: options.tags || [],
        priority: options.priority || 0,
        modelType: options.modelType,
        parentModel: options.parentModel,
        userProblem: options.userProblem,
        decisionAxis: options.decisionAxis,
        relatedHints: options.relatedHints || {},
        adversarialRisk: options.adversarialRisk,
    };
}

const catalog = [
    entry('rag', 'RAG', 'technique', [wikipedia('Retrieval-augmented_generation'), url('https://www.ibm.com/think/topics/retrieval-augmented-generation')], { aliases: ['retrieval augmented generation'], tags: ['retrieval', 'generation'], priority: 90 }),
    entry('llm', 'LLM', 'concept', [wikipedia('Large_language_model'), url('https://www.ibm.com/think/topics/large-language-models')], { aliases: ['large language model'], tags: ['language-model', 'foundation-model'], priority: 100 }),
    entry('mcp', 'MCP', 'framework', [url('https://modelcontextprotocol.io/introduction'), repo('modelcontextprotocol/specification')], { aliases: ['model context protocol'], tags: ['protocol', 'tool-use'], priority: 95 }),
    entry('agent', 'AI Agent', 'concept', [wikipedia('Intelligent_agent'), url('https://www.ibm.com/think/topics/ai-agents')], { aliases: ['ai agent', 'intelligent agent'], tags: ['autonomy', 'workflow'], priority: 100 }),
    entry('api', 'API', 'concept', [wikipedia('API'), url('https://aws.amazon.com/what-is/api/')], { aliases: ['application programming interface'], tags: ['integration', 'infrastructure'], priority: 90 }),
    entry('benchmark', 'Benchmark', 'concept', [wikipedia('Benchmark_(computing)'), url('https://huggingface.co/docs/evaluate/index')], { aliases: ['evaluation benchmark'], tags: ['evaluation', 'measurement'], priority: 88 }),
    entry('claude-code', 'Claude Code', 'tool', [url('https://docs.anthropic.com/en/docs/claude-code/overview'), url('https://www.anthropic.com/claude-code')], { aliases: ['claude code'], tags: ['coding-agent', 'developer-tools'], priority: 96 }),
    entry('gemini', 'Gemini', 'model', [wikipedia('Gemini_(language_model)'), url('https://deepmind.google/technologies/gemini/')], { aliases: ['google gemini'], tags: ['google', 'multimodal'], priority: 98, modelType: 'family' }),
    entry('gemma', 'Gemma', 'model', [wikipedia('Gemma_(language_model)'), url('https://ai.google.dev/gemma')], { aliases: ['google gemma'], tags: ['open-model', 'google'], priority: 88, modelType: 'family' }),
    entry('token', 'Token', 'concept', [wikipedia('Tokenization_(lexical_analysis)'), url('https://platform.openai.com/tokenizer')], { aliases: ['tokenization'], tags: ['language-model', 'context-window'], priority: 85 }),
    entry('transformer', 'Transformer', 'concept', [wikipedia('Transformer_(deep_learning_architecture)'), url('https://research.google/pubs/attention-is-all-you-need/')], { tags: ['architecture', 'attention'], priority: 88 }),
    entry('fine-tuning', 'Fine-tuning', 'technique', [wikipedia('Fine-tuning_(deep_learning)'), url('https://platform.openai.com/docs/guides/fine-tuning')], { aliases: ['fine tuning'], tags: ['adaptation', 'training'], priority: 86 }),
    entry('prompt-engineering', 'Prompt Engineering', 'technique', [wikipedia('Prompt_engineering'), url('https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview')], { aliases: ['prompt engineering'], tags: ['prompting', 'instruction'], priority: 92 }),
    entry('embedding', 'Embedding', 'concept', [wikipedia('Word_embedding'), url('https://platform.openai.com/docs/guides/embeddings')], {
        aliases: ['vector embedding'],
        tags: ['vectors', 'retrieval'],
        priority: 86,
        userProblem: '검색 품질이 모델 답변보다 먼저 갈리고 있는지',
        decisionAxis: '임베딩 모델 품질, 벡터 저장 방식, 검색 파이프라인 중 어디가 병목인지',
        relatedHints: {
            rag: '검색 단계가 약하면 RAG 답변도 같이 흔들린다는 점을 같이 보게 해 준다.',
            llamaindex: '임베딩을 실제 인덱싱과 검색 흐름에 어떻게 붙이는지 이해하는 데 이어진다.',
            'vector-db': '벡터를 어디에 저장하고 어떤 필터·검색 전략으로 꺼낼지까지 같이 보게 해 준다.',
            pinecone: '임베딩 품질이 아니라 운영형 벡터 스토어 선택으로 문제가 넘어가는 지점을 구분하게 해 준다.',
        },
        adversarialRisk: '임베딩 품질 문제를 LLM 답변 문제로 착각하면 검색 단계 병목을 놓치기 쉬워.',
    }),
    entry('attention', 'Attention', 'concept', [wikipedia('Attention_(machine_learning)'), url('https://research.google/pubs/attention-is-all-you-need/')], { tags: ['architecture', 'transformer'], priority: 84 }),
    entry('rlhf', 'RLHF', 'technique', [wikipedia('Reinforcement_learning_from_human_feedback'), url('https://huggingface.co/blog/rlhf')], { aliases: ['reinforcement learning from human feedback'], tags: ['alignment', 'training'], priority: 82 }),
    entry('diffusion', 'Diffusion Model', 'concept', [wikipedia('Diffusion_model'), url('https://stability.ai/blog/stable-diffusion-public-release')], {
        aliases: ['diffusion model'],
        tags: ['image-generation', 'generative-ai'],
        priority: 82,
        userProblem: '이미지 생성 뉴스에서 모델 이름보다 생성 방식 차이가 중요한지',
        decisionAxis: '생성 품질, 제어 가능성, 추론 비용 중 무엇이 핵심인지',
        relatedHints: {
            'stable-diffusion': '확산 모델이 실제 제품 이름으로 내려오면 어떤 라인업이 되는지 이어서 보게 해 준다.',
            'dall-e': '같은 이미지 생성이라도 제품형 서비스와 모델 계열 설명이 어떻게 갈리는지 비교하게 해 준다.',
            flux: '확산 계열 이후 구현이 어떻게 달라졌는지와 배포 방식 차이를 같이 보게 해 준다.',
            imagen: '연구 발표형 이미지 생성 모델이 제품 문맥으로 내려올 때 무엇을 더 봐야 하는지 비교하게 해 준다.',
        },
        adversarialRisk: '이미지 생성 모델 이름만 외우고 생성 방식 차이를 놓치면 발표문을 과장되게 읽기 쉽다.',
    }),
    entry('multimodal', 'Multimodal AI', 'concept', [wikipedia('Multimodal_learning'), url('https://deepmind.google/technologies/gemini/')], {
        aliases: ['multimodal ai'],
        tags: ['vision', 'audio'],
        priority: 90,
        userProblem: '텍스트 모델 뉴스가 아니라 입력과 출력 범위가 넓어진 변화인지',
        decisionAxis: '이미지 이해, 음성 처리, 비디오 입력 중 실제로 지원 범위가 어디까지인지',
        relatedHints: {
            'vision-language-model': '이미지와 텍스트를 같이 다루는 축이 멀티모달 안에서 어디쯤인지 구분하게 해 준다.',
            whisper: '오디오 이해가 멀티모달 전체와 같은 말은 아니라는 점을 비교하게 해 준다.',
            'speech-to-text': '음성 입력 처리만 필요한지, 더 넓은 멀티모달 시스템을 보는지 가르게 해 준다.',
            'text-to-speech': '음성 출력 계층이 멀티모달 전체와 어떻게 다른지 비교하게 해 준다.',
        },
        adversarialRisk: '멀티모달이라는 말만 보고 이미지, 음성, 비디오 지원이 전부 다 된다고 읽으면 실제 기능 범위를 과대평가하기 쉽다.',
    }),
    entry('vibe-coding', 'Vibe Coding', 'technique', [url('https://en.wikipedia.org/wiki/Vibe_coding'), url('https://www.anthropic.com/news/claude-3-7-sonnet')], { aliases: ['vibe coding'], tags: ['coding-agent', 'workflow'], priority: 80 }),
    entry('vector-db', 'Vector Database', 'tool', [wikipedia('Vector_database'), url('https://www.pinecone.io/learn/vector-database/')], {
        aliases: ['vector database'],
        tags: ['retrieval', 'search'],
        priority: 85,
        userProblem: 'RAG에서 문서를 어디에 저장하고 어떤 검색 엔진으로 꺼낼지',
        decisionAxis: '검색 정확도보다 운영 방식과 필터링·하이브리드 검색 요구가 더 큰 선택 기준인지',
        relatedHints: {
            pinecone: '완전 관리형 벡터 DB를 고를 때 어떤 운영 부담을 넘기는지 비교하게 해 준다.',
            qdrant: '직접 운영 가능한 오픈소스 대안과 비교할 때 제어권과 배포 자유도를 보게 해 준다.',
            weaviate: '모듈형 검색과 스키마 설계까지 같이 보려는지 비교하게 해 준다.',
            chroma: '프로토타입용 가벼운 저장소와 운영형 벡터 DB를 가르는 기준으로 같이 본다.',
        },
        adversarialRisk: '벡터 DB라는 큰 묶음만 보면 실제론 관리형 SaaS, 오픈소스 서버형, 로컬 임베디드형 차이를 놓치기 쉬워.',
    }),
    entry('tokenizer', 'Tokenizer', 'tool', [wikipedia('Tokenization_(lexical_analysis)'), url('https://platform.openai.com/tokenizer')], { aliases: ['tokenizer'], tags: ['tokens', 'preprocessing'], priority: 78 }),
    entry('context-window', 'Context Window', 'concept', [url('https://en.wikipedia.org/wiki/Large_language_model'), url('https://docs.anthropic.com/en/docs/build-with-claude/context-windows')], { aliases: ['context length'], tags: ['tokens', 'memory'], priority: 88 }),
    entry('hallucination', 'Hallucination', 'concept', [wikipedia('Hallucination_(artificial_intelligence)'), url('https://www.ibm.com/think/topics/ai-hallucinations')], { aliases: ['ai hallucination'], tags: ['reliability', 'safety'], priority: 84 }),
    entry('inference', 'Inference', 'concept', [wikipedia('Statistical_inference'), url('https://developers.google.com/machine-learning/glossary#inference')], { aliases: ['model inference'], tags: ['serving', 'runtime'], priority: 80 }),
    entry('reasoning', 'Reasoning Model', 'concept', [url('https://platform.openai.com/docs/guides/reasoning-best-practices'), url('https://www.anthropic.com/news/visible-extended-thinking')], { aliases: ['reasoning model'], tags: ['thinking', 'planning'], priority: 92 }),
    entry('distillation', 'Distillation', 'technique', [wikipedia('Knowledge_distillation'), url('https://platform.openai.com/docs/guides/distillation')], { aliases: ['knowledge distillation'], tags: ['training', 'efficiency'], priority: 84 }),
    entry('quantization', 'Quantization', 'technique', [wikipedia('Quantization_(signal_processing)'), url('https://huggingface.co/docs/transformers/quantization/overview')], { aliases: ['model quantization'], tags: ['efficiency', 'deployment'], priority: 88 }),
    entry('synthetic-data', 'Synthetic Data', 'technique', [wikipedia('Synthetic_data'), url('https://www.ibm.com/think/topics/synthetic-data')], { aliases: ['synthetic data'], tags: ['training-data', 'evaluation'], priority: 74 }),
    entry('mixture-of-experts', 'Mixture of Experts', 'concept', [wikipedia('Mixture_of_experts'), url('https://mistral.ai/news/mixtral-of-experts')], { aliases: ['moe'], tags: ['architecture', 'scaling'], priority: 84 }),
    entry('alignment', 'Alignment', 'concept', [wikipedia('AI_alignment'), url('https://www.anthropic.com/research/constitutional-ai-harmlessness-from-ai-feedback')], { aliases: ['ai alignment'], tags: ['safety', 'training'], priority: 86 }),
    entry('guardrail', 'Guardrail', 'technique', [url('https://www.ibm.com/think/topics/ai-guardrails'), url('https://docs.anthropic.com/en/docs/test-and-evaluate/strengthen-guardrails/overview')], { aliases: ['guardrails'], tags: ['safety', 'policy'], priority: 82 }),
    entry('eval', 'Eval', 'technique', [url('https://platform.openai.com/docs/guides/evals'), url('https://huggingface.co/docs/evaluate/index')], { aliases: ['evaluation'], tags: ['testing', 'benchmark'], priority: 90 }),
    entry('red-teaming', 'Red Teaming', 'technique', [url('https://www.ibm.com/think/topics/red-teaming'), url('https://www.anthropic.com/news/red-teaming-language-models-to-reduce-harms-methods-scaling-behaviors-and-lessons-learned')], { aliases: ['red teaming'], tags: ['safety', 'testing'], priority: 76 }),
    entry('function-calling', 'Function Calling', 'technique', [url('https://platform.openai.com/docs/guides/function-calling'), url('https://docs.anthropic.com/en/docs/agents-and-tools/tool-use/overview')], { aliases: ['tool calling'], tags: ['tool-use', 'api'], priority: 90 }),
    entry('tool-use', 'Tool Use', 'technique', [url('https://docs.anthropic.com/en/docs/agents-and-tools/tool-use/overview'), url('https://platform.openai.com/docs/guides/function-calling')], { aliases: ['tool use'], tags: ['agents', 'function-calling'], priority: 90 }),
    entry('long-context', 'Long Context', 'concept', [url('https://docs.anthropic.com/en/docs/build-with-claude/context-windows'), url('https://deepmind.google/technologies/gemini/')], { aliases: ['long context'], tags: ['context-window', 'memory'], priority: 86 }),
    entry('chain-of-thought', 'Chain-of-Thought', 'technique', [wikipedia('Chain-of-thought_prompting'), url('https://research.google/blog/language-models-perform-reasoning-via-chain-of-thought/')], { aliases: ['cot'], tags: ['reasoning', 'prompting'], priority: 82 }),
    entry('prompt-caching', 'Prompt Caching', 'technique', [url('https://platform.openai.com/docs/guides/prompt-caching'), url('https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching')], { aliases: ['cache reuse'], tags: ['efficiency', 'inference'], priority: 78 }),
    entry('speech-to-text', 'Speech to Text', 'technique', [wikipedia('Speech_recognition'), url('https://platform.openai.com/docs/guides/speech-to-text')], {
        aliases: ['asr'],
        tags: ['audio', 'transcription'],
        priority: 74,
        userProblem: '음성 입력을 텍스트로 바꾸는 단계에서 정확도와 지연 중 어디가 병목인지',
        decisionAxis: '인식 정확도, 스트리밍 지연, 운영비 중 어디를 먼저 맞춰야 하는지',
        relatedHints: {
            whisper: '대표적인 음성 인식 모델이 실제로 어떤 품질 기준을 보여주는지 이어서 보게 해 준다.',
            multimodal: '음성 입력 처리 하나와 멀티모달 전체 시스템은 범위가 다르다는 점을 구분하게 해 준다.',
            'text-to-speech': '입력을 텍스트로 바꾸는 문제와 출력을 음성으로 만드는 문제를 분리해 보게 해 준다.',
        },
        adversarialRisk: '음성 기능 전체를 한 덩어리로 보면 인식과 합성의 병목이 어디서 갈리는지 놓치기 쉽다.',
    }),
    entry('text-to-speech', 'Text to Speech', 'technique', [wikipedia('Speech_synthesis'), url('https://platform.openai.com/docs/guides/text-to-speech')], {
        aliases: ['tts'],
        tags: ['audio', 'voice'],
        priority: 74,
        userProblem: '텍스트를 음성으로 내보낼 때 자연스러움과 지연 중 어디가 더 중요한지',
        decisionAxis: '음질, 스트리밍 지연, 비용 중 무엇을 먼저 맞춰야 하는지',
        relatedHints: {
            multimodal: '음성 출력 계층이 멀티모달 전체와 같은 말은 아니라는 점을 구분하게 해 준다.',
            whisper: '입력 인식 모델과 출력 합성 모델은 선택 기준이 다르다는 점을 비교하게 해 준다.',
            'speech-to-text': '음성 입출력 전체를 묶어 보지 말고 어느 단계 문제인지 분리하게 해 준다.',
        },
        adversarialRisk: 'TTS를 단순 보이스 효과로만 보면 지연과 운영비 같은 제품 문제를 놓치기 쉽다.',
    }),
    entry('grounding', 'Grounding', 'technique', [url('https://ai.google.dev/gemini-api/docs/grounding'), url('https://cloud.google.com/vertex-ai/generative-ai/docs/grounding/overview')], { aliases: ['retrieval grounding'], tags: ['retrieval', 'reliability'], priority: 76 }),
    entry('memory', 'Memory', 'concept', [url('https://docs.anthropic.com/en/docs/agents-and-tools/context-engineering'), url('https://blog.langchain.dev/short-term-memory-agent/')], { aliases: ['agent memory', 'ai memory'], tags: ['agents', 'context-window'], priority: 78 }),
    entry('vision-language-model', 'Vision-Language Model', 'concept', [wikipedia('Multimodal_learning'), url('https://huggingface.co/tasks/image-text-to-text')], {
        aliases: ['vlm'],
        tags: ['multimodal', 'vision'],
        priority: 76,
        userProblem: '이미지를 읽는 모델 뉴스인지, 이미지까지 생성하는 모델 뉴스인지',
        decisionAxis: '이미지 이해, 텍스트 생성, 실시간 입력 처리 중 어디가 핵심인지',
        relatedHints: {
            gemini: '멀티모달 제품 모델이 VLM 개념을 실제 서비스로 어떻게 묶는지 이어서 보게 해 준다.',
            'gpt-4o': '범용 멀티모달 모델이 이미지 이해를 어디까지 제품 기능으로 내놓는지 비교하게 해 준다.',
            multimodal: 'VLM이 멀티모달 전체 안에서 어느 범위를 가리키는지 상위 개념과 같이 보게 해 준다.',
        },
        adversarialRisk: '이미지 이해 모델과 이미지 생성 모델을 같은 축으로 읽으면 제품 기능을 잘못 짚기 쉽다.',
    }),
    entry('small-language-model', 'Small Language Model', 'concept', [url('https://azure.microsoft.com/en-us/resources/cloud-computing-dictionary/what-is-a-small-language-model'), url('https://huggingface.co/blog/smollm')], { aliases: ['slm'], tags: ['efficiency', 'on-device'], priority: 70 }),
    entry('langchain', 'LangChain', 'framework', [repo('langchain-ai/langchain'), url('https://www.langchain.com/')], { tags: ['agents', 'workflow'], priority: 94 }),
    entry('llamaindex', 'LlamaIndex', 'framework', [repo('run-llama/llama_index'), url('https://www.llamaindex.ai/')], { tags: ['retrieval', 'agents'], priority: 88 }),
    entry('vllm', 'vLLM', 'tool', [repo('vllm-project/vllm'), url('https://docs.vllm.ai/')], { tags: ['inference', 'serving'], priority: 90 }),
    entry('ollama', 'Ollama', 'tool', [repo('ollama/ollama'), url('https://ollama.com/')], { tags: ['local-ai', 'inference'], priority: 90 }),
    entry('llama.cpp', 'llama.cpp', 'tool', [repo('ggerganov/llama.cpp'), url('https://github.com/ggerganov/llama.cpp')], { aliases: ['llamacpp'], tags: ['local-ai', 'gguf'], priority: 92 }),
    entry('gguf', 'GGUF', 'framework', [url('https://github.com/ggerganov/llama.cpp/blob/master/gguf-py/README.md'), url('https://huggingface.co/docs/hub/gguf')], { tags: ['local-ai', 'model-format'], priority: 84 }),
    entry('openrouter', 'OpenRouter', 'tool', [url('https://openrouter.ai/docs/overview/introduction'), url('https://openrouter.ai/')], { tags: ['api', 'routing'], priority: 82 }),
    entry('cursor', 'Cursor', 'tool', [url('https://www.cursor.com/'), url('https://docs.cursor.com/')], { tags: ['coding-agent', 'editor'], priority: 94 }),
    entry('windsurf', 'Windsurf', 'tool', [url('https://windsurf.com/'), url('https://docs.windsurf.com/')], { tags: ['coding-agent', 'editor'], priority: 82 }),
    entry('aider', 'Aider', 'tool', [repo('Aider-AI/aider'), url('https://aider.chat/')], { tags: ['coding-agent', 'cli'], priority: 82 }),
    entry('cline', 'Cline', 'tool', [repo('cline/cline'), url('https://docs.cline.bot/')], { tags: ['coding-agent', 'vs-code'], priority: 80 }),
    entry('continue', 'Continue', 'tool', [repo('continuedev/continue'), url('https://docs.continue.dev/')], { tags: ['coding-agent', 'editor'], priority: 80 }),
    entry('lm-studio', 'LM Studio', 'tool', [url('https://lmstudio.ai/'), url('https://lmstudio.ai/docs/welcome')], { tags: ['local-ai', 'desktop'], priority: 78 }),
    entry('comfyui', 'ComfyUI', 'tool', [repo('comfyanonymous/ComfyUI'), url('https://www.comfy.org/')], { tags: ['image-generation', 'workflow'], priority: 72 }),
    entry('gradio', 'Gradio', 'framework', [repo('gradio-app/gradio'), url('https://www.gradio.app/')], { tags: ['demo', 'ui'], priority: 76 }),
    entry('streamlit', 'Streamlit', 'framework', [repo('streamlit/streamlit'), url('https://streamlit.io/')], { tags: ['app', 'ui'], priority: 74 }),
    entry('pytorch', 'PyTorch', 'framework', [wikipedia('PyTorch'), url('https://pytorch.org/')], { tags: ['training', 'deep-learning'], priority: 88 }),
    entry('tensorflow', 'TensorFlow', 'framework', [wikipedia('TensorFlow'), url('https://www.tensorflow.org/')], { tags: ['training', 'deep-learning'], priority: 76 }),
    entry('jax', 'JAX', 'framework', [repo('jax-ml/jax'), url('https://jax.readthedocs.io/en/latest/')], { tags: ['training', 'research'], priority: 76 }),
    entry('onnx', 'ONNX', 'framework', [wikipedia('Open_Neural_Network_Exchange'), url('https://onnx.ai/')], { tags: ['interoperability', 'deployment'], priority: 74 }),
    entry('triton', 'Triton Inference Server', 'tool', [repo('triton-inference-server/server'), url('https://developer.nvidia.com/triton-inference-server')], { aliases: ['triton inference server'], tags: ['serving', 'inference'], priority: 70 }),
    entry('ray', 'Ray', 'framework', [repo('ray-project/ray'), url('https://www.ray.io/')], { tags: ['distributed', 'training'], priority: 70 }),
    entry('kubeflow', 'Kubeflow', 'framework', [repo('kubeflow/kubeflow'), url('https://www.kubeflow.org/')], { tags: ['mlops', 'kubernetes'], priority: 66 }),
    entry('mlflow', 'MLflow', 'tool', [repo('mlflow/mlflow'), url('https://mlflow.org/')], { tags: ['mlops', 'tracking'], priority: 68 }),
    entry('bentoml', 'BentoML', 'tool', [repo('bentoml/BentoML'), url('https://www.bentoml.com/')], { tags: ['serving', 'deployment'], priority: 68 }),
    entry('weights-and-biases', 'Weights & Biases', 'tool', [url('https://wandb.ai/site'), url('https://docs.wandb.ai/')], { aliases: ['wandb'], tags: ['mlops', 'tracking'], priority: 70 }),
    entry('modal', 'Modal', 'tool', [url('https://modal.com/'), url('https://modal.com/docs/guide')], { tags: ['deployment', 'serverless'], priority: 72 }),
    entry('replicate', 'Replicate', 'tool', [url('https://replicate.com/'), url('https://replicate.com/docs')], { tags: ['api', 'inference'], priority: 70 }),
    entry('vercel-ai-sdk', 'Vercel AI SDK', 'framework', [repo('vercel/ai'), url('https://sdk.vercel.ai/docs')], { aliases: ['ai sdk'], tags: ['application', 'frontend'], priority: 74 }),
    entry('openai-api', 'OpenAI API', 'tool', [url('https://platform.openai.com/docs/overview'), url('https://platform.openai.com/docs/api-reference')], { tags: ['api', 'application'], priority: 90 }),
    entry('anthropic-api', 'Anthropic API', 'tool', [url('https://docs.anthropic.com/en/docs/overview'), url('https://docs.anthropic.com/en/api/getting-started')], { tags: ['api', 'application'], priority: 88 }),
    entry('google-ai-studio', 'Google AI Studio', 'tool', [url('https://ai.google.dev/gemini-api/docs/ai-studio-quickstart'), url('https://aistudio.google.com/')], { tags: ['api', 'prototyping'], priority: 74 }),
    entry('hugging-face', 'Hugging Face', 'tool', [wikipedia('Hugging_Face'), url('https://huggingface.co/docs/hub/index')], { tags: ['model-hub', 'community'], priority: 90 }),
    entry('sglang', 'SGLang', 'tool', [repo('sgl-project/sglang'), url('https://docs.sglang.ai/')], { tags: ['inference', 'serving'], priority: 70 }),
    entry('deepspeed', 'DeepSpeed', 'framework', [repo('deepspeedai/DeepSpeed'), url('https://www.deepspeed.ai/')], { tags: ['training', 'optimization'], priority: 72 }),
    entry('langgraph', 'LangGraph', 'framework', [repo('langchain-ai/langgraph'), url('https://www.langchain.com/langgraph')], { tags: ['agents', 'workflow'], priority: 82 }),
    entry('autogen', 'AutoGen', 'framework', [repo('microsoft/autogen'), url('https://microsoft.github.io/autogen/stable/')], { tags: ['agents', 'multi-agent'], priority: 78 }),
    entry('crewai', 'CrewAI', 'framework', [repo('crewAIInc/crewAI'), url('https://docs.crewai.com/')], { tags: ['agents', 'workflow'], priority: 76 }),
    entry('n8n', 'n8n', 'tool', [wikipedia('N8n'), url('https://docs.n8n.io/')], { tags: ['automation', 'workflow'], priority: 80 }),
    entry('supabase', 'Supabase', 'tool', [wikipedia('Supabase'), url('https://supabase.com/docs')], { tags: ['database', 'backend'], priority: 74 }),
    entry('pinecone', 'Pinecone', 'tool', [wikipedia('Pinecone_(company)'), url('https://docs.pinecone.io/')], {
        tags: ['vector-db', 'retrieval'],
        priority: 78,
        userProblem: '벡터 검색을 빨리 붙이고 싶지만 인프라를 직접 운영하고 싶지 않은지',
        decisionAxis: '완전 관리형 SaaS의 편의성과 비용을 감수할 만한지',
        relatedHints: {
            weaviate: '오픈소스 기반 서버형과 비교할 때 관리형 편의성이 얼마나 중요한지 보게 해 준다.',
            chroma: '개발 단계 임베디드 저장소와 프로덕션 SaaS를 구분하는 기준으로 같이 본다.',
            qdrant: '직접 운영 가능한 오픈소스 대안과 비교할 때 제어권과 운영 부담 차이를 보게 해 준다.',
            rag: '왜 이런 관리형 벡터 DB가 필요한지 상위 검색 구조를 같이 잡게 해 준다.',
        },
        adversarialRisk: '벡터 검색 성능만 보고 고르면, 실제론 클라우드 종속성과 비용 구조를 나중에야 체감하게 되기 쉬워.',
    }),
    entry('weaviate', 'Weaviate', 'tool', [wikipedia('Weaviate'), url('https://docs.weaviate.io/')], {
        tags: ['vector-db', 'retrieval'],
        priority: 74,
        userProblem: '벡터 검색에 필터링, 모듈 연결, 스키마 설계까지 한 번에 묶고 싶은지',
        decisionAxis: '검색 엔진 하나보다 데이터 모델과 확장 모듈까지 같이 고를 필요가 있는지',
        relatedHints: {
            pinecone: '완전 관리형 서비스와 오픈소스 서버형 중 어디에 무게를 둘지 비교하게 해 준다.',
            chroma: '앱 안에 가볍게 넣는 저장소가 아니라 서비스용 데이터 모델을 다루는 쪽인지 구분하게 해 준다.',
            qdrant: '오픈소스 기반끼리 비교할 때 API 감각과 기능 구성 차이를 보게 해 준다.',
            rag: '검색 파이프라인 안에서 벡터 DB를 어떻게 설계하는지 상위 맥락을 같이 잡게 해 준다.',
        },
        adversarialRisk: '벡터 DB라는 이름만 같다고 같은 급의 제품으로 보면, 모듈 구조와 데이터 모델링 난도를 과소평가하기 쉬워.',
    }),
    entry('chroma', 'Chroma', 'tool', [repo('chroma-core/chroma'), url('https://docs.trychroma.com/')], {
        tags: ['vector-db', 'retrieval'],
        priority: 72,
        userProblem: '프로토타입 단계에서 가볍게 붙일 저장소가 필요한지, 운영형 벡터 DB가 필요한지',
        decisionAxis: '임베디드·로컬 중심 도구로 충분한지 아니면 별도 서비스형 DB가 필요한지',
        relatedHints: {
            pinecone: '프로토타입용 로컬 스토어와 완전 관리형 SaaS의 간극을 비교하게 해 준다.',
            weaviate: '가벼운 개발용 스택과 기능 많은 서버형 벡터 DB 차이를 보게 해 준다.',
            qdrant: '오픈소스 서버형으로 올라갈 필요가 있는지 판단하는 비교축이 된다.',
            rag: '왜 벡터 저장소를 붙이는지 상위 검색 구조를 다시 잡게 해 준다.',
        },
        adversarialRisk: '벡터 DB라는 말만 보고 바로 운영형 제품 후보로 올리면, 실제론 개발 편의 도구에 더 가까운 경우를 놓치기 쉬워.',
    }),
    entry('faiss', 'FAISS', 'tool', [wikipedia('Faiss'), url('https://github.com/facebookresearch/faiss')], { tags: ['vector-search', 'retrieval'], priority: 72 }),
    entry('qdrant', 'Qdrant', 'tool', [repo('qdrant/qdrant'), url('https://qdrant.tech/documentation/')], {
        tags: ['vector-db', 'retrieval'],
        priority: 72,
        userProblem: '벡터 검색을 제품에 붙이려는데 운영 제어권과 검색 성능을 둘 다 챙길 수 있는지',
        decisionAxis: '관리형 서비스 대신 직접 운영 가능한 오픈소스 벡터 DB를 골라도 되는지',
        relatedHints: {
            pinecone: '완전 관리형 벡터 DB와 비교할 때 제어권과 운영 부담이 어떻게 갈리는지 보게 해 준다.',
            weaviate: '오픈소스 서버형끼리 비교할 때 기능 구성과 데이터 모델 감각 차이를 잡게 해 준다.',
            chroma: '개발용 임베디드 스토어에서 운영형 서버로 올라갈 필요가 있는지 판단하게 해 준다.',
            rag: '왜 Qdrant 같은 벡터 DB가 검색 파이프라인에서 필요한지 상위 맥락을 같이 잡게 해 준다.',
        },
        adversarialRisk: '오픈소스 벡터 DB라고만 읽으면 자체 운영 비용과 관리형 서비스 대체 가능 범위를 둘 다 과대평가하기 쉬워.',
    }),
    entry('gpt-4o', 'GPT-4o', 'model', [wikipedia('GPT-4o'), url('https://openai.com/index/hello-gpt-4o/')], { tags: ['openai', 'multimodal'], priority: 90, modelType: 'version' }),
    entry('o1', 'o1', 'model', [url('https://openai.com/index/introducing-openai-o1-preview/'), url('https://platform.openai.com/docs/guides/reasoning-best-practices')], { tags: ['openai', 'reasoning'], priority: 84, modelType: 'version' }),
    entry('o3', 'o3', 'model', [url('https://platform.openai.com/docs/models/o3'), url('https://platform.openai.com/docs/pricing')], { tags: ['openai', 'reasoning'], priority: 88, modelType: 'version' }),
    entry('claude', 'Claude', 'model', [wikipedia('Claude_(language_model)'), url('https://www.anthropic.com/claude')], { tags: ['anthropic', 'assistant'], priority: 94, modelType: 'family' }),
    entry('claude-opus', 'Claude Opus', 'model', [url('https://www.anthropic.com/claude/opus'), url('https://docs.anthropic.com/en/docs/about-claude/models')], { tags: ['anthropic', 'reasoning'], priority: 86, modelType: 'family', parentModel: 'claude' }),
    entry('claude-sonnet', 'Claude Sonnet', 'model', [url('https://www.anthropic.com/claude/sonnet'), url('https://docs.anthropic.com/en/docs/about-claude/models')], { tags: ['anthropic', 'application'], priority: 86, modelType: 'family', parentModel: 'claude' }),
    entry('claude-sonnet-4-5', 'Claude Sonnet 4.5', 'model', [url('https://www.anthropic.com/news/claude-sonnet-4-5'), url('https://docs.anthropic.com/en/docs/about-claude/models')], { aliases: ['claude sonnet 4.5'], tags: ['anthropic', 'application'], priority: 92, modelType: 'version', parentModel: 'claude-sonnet' }),
    entry('deepseek-r1', 'DeepSeek R1', 'model', [repo('deepseek-ai/DeepSeek-R1'), url('https://api-docs.deepseek.com/news/news250120')], { tags: ['reasoning', 'open-model'], priority: 90, modelType: 'version' }),
    entry('qwen', 'Qwen', 'model', [wikipedia('Qwen'), url('https://qwenlm.github.io/')], { tags: ['alibaba', 'open-model'], priority: 88, modelType: 'family' }),
    entry('llama', 'Llama', 'model', [wikipedia('Llama_(language_model)'), url('https://ai.meta.com/llama/')], { tags: ['meta', 'open-model'], priority: 90, modelType: 'family' }),
    entry('mistral', 'Mistral', 'model', [wikipedia('Mistral_AI'), url('https://mistral.ai/technology/')], { tags: ['mistral', 'open-weight'], priority: 84, modelType: 'family' }),
    entry('mixtral', 'Mixtral', 'model', [url('https://mistral.ai/news/mixtral-of-experts'), url('https://huggingface.co/mistralai/Mixtral-8x7B-v0.1')], { tags: ['mistral', 'moe'], priority: 80, modelType: 'version', parentModel: 'mistral' }),
    entry('phi', 'Phi', 'model', [wikipedia('Phi_(language_model)'), url('https://azure.microsoft.com/en-us/blog/introducing-phi-4/')], { tags: ['microsoft', 'small-language-model'], priority: 78, modelType: 'family' }),
    entry('grok', 'Grok', 'model', [wikipedia('Grok_(chatbot)'), url('https://x.ai/blog')], { tags: ['xai', 'assistant'], priority: 72, modelType: 'family' }),
    entry('sora', 'Sora', 'model', [wikipedia('Sora_(text-to-video_model)'), url('https://openai.com/sora')], { tags: ['video-generation', 'openai'], priority: 88, modelType: 'family' }),
    entry('whisper', 'Whisper', 'model', [wikipedia('Whisper_(speech_recognition_system)'), url('https://openai.com/index/whisper/')], { tags: ['audio', 'transcription'], priority: 76, modelType: 'family' }),
    entry('dall-e', 'DALL-E', 'model', [wikipedia('DALL-E'), url('https://openai.com/dall-e-3')], { tags: ['image-generation', 'openai'], priority: 78, modelType: 'family' }),
    entry('stable-diffusion', 'Stable Diffusion', 'model', [wikipedia('Stable_Diffusion'), url('https://stability.ai/stable-image')], { tags: ['image-generation', 'open-model'], priority: 82, modelType: 'family' }),
    entry('flux', 'FLUX.1', 'model', [url('https://blackforestlabs.ai/announcing-black-forest-labs/'), url('https://huggingface.co/black-forest-labs')], { tags: ['image-generation', 'open-weight'], priority: 78, modelType: 'version' }),
    entry('veo', 'Veo', 'model', [url('https://deepmind.google/models/veo/'), url('https://blog.google/technology/google-deepmind/veo-2/')], { tags: ['video-generation', 'google'], priority: 76, modelType: 'family' }),
    entry('lyria', 'Lyria', 'model', [url('https://deepmind.google/models/lyria/'), url('https://blog.google/technology/google-deepmind/lyria-a-new-way-to-create-music-with-generative-ai/')], { tags: ['music-generation', 'google'], priority: 76, modelType: 'family' }),
    entry('imagen', 'Imagen', 'model', [wikipedia('Imagen_(Google)'), url('https://deepmind.google/models/imagen/')], { tags: ['image-generation', 'google'], priority: 76, modelType: 'family' }),
    entry('gemini-2.5', 'Gemini 2.5', 'model', [url('https://deepmind.google/technologies/gemini/'), url('https://ai.google.dev/gemini-api/docs/models')], { tags: ['google', 'reasoning'], priority: 86, modelType: 'version', parentModel: 'gemini' }),
    entry('gemma-3', 'Gemma 3', 'model', [url('https://ai.google.dev/gemma'), url('https://blog.google/technology/developers/gemma-3/')], { tags: ['google', 'open-model'], priority: 74, modelType: 'version', parentModel: 'gemma' }),
    entry('openai', 'OpenAI', 'tool', [wikipedia('OpenAI'), url('https://openai.com/')], { tags: ['company', 'model-lab'], priority: 92 }),
    entry('anthropic', 'Anthropic', 'tool', [wikipedia('Anthropic'), url('https://www.anthropic.com/')], { tags: ['company', 'model-lab'], priority: 88 }),
    entry('google-deepmind', 'Google DeepMind', 'tool', [wikipedia('Google_DeepMind'), url('https://deepmind.google/')], { tags: ['company', 'research'], priority: 86 }),
    entry('copilot', 'GitHub Copilot', 'tool', [wikipedia('GitHub_Copilot'), url('https://github.com/features/copilot')], { tags: ['coding-agent', 'developer-tools'], priority: 86 }),
    entry('perplexity', 'Perplexity', 'tool', [wikipedia('Perplexity_AI'), url('https://www.perplexity.ai/hub')], { tags: ['search', 'assistant'], priority: 72 }),
];

module.exports = {
    catalog,
};
